in_dir = "alice/frames"
mask_dir = "alice/masks"
out_dir = "outputs/example_video"
width = 476
height = 360

[prompts]
ghost = "a ghostly apparition, fog, art by greg rutkowski"

[[keyframes]]
frame = 1                   # the first keyframe should always be frame 1
# Input images are named cheshire/IM0001.png, cheshire/IM0002.png, etc.
# We want to start at IM0278 and increment from there.
input_image = "cheshire/IM{0278}.png"
seed = 89075690
prompt = "ghost"
scale = 8.0
strength = 0.0
steps = 50

[[keyframes]]
duration = 50
strength = 0.7

[[keyframes]]
duration = 50
strength = 0.0
